targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        options:
          auto_register: true
          class_name_pattern:
            ".*Repository$|.*Repository[^.]*$|.*DataSource$|.*UseCase$"
          file_name_pattern: "([a-z_]*).dart$"
