name: Flutter CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ] # Adjust if your main branch has a different name (e.g., master)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4 # Checks-out your repository under $GITHUB_WORKSPACE

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2' # Use the version specified in README.md
          channel: 'stable'
          cache: true # Enable caching for faster builds

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test
