name: Flutter Format and Analyze

on:
  push:
    branches: [ main, 'devin/**' ]
  pull_request:
    branches: [ main ]

jobs:
  format-and-analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Format code
        run: dart format -o write .
      - name: Analyze code
        run: flutter analyze
